# Generated by Django 3.2 on 2024-07-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_last_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='last_sms',
            field=models.CharField(default=1720370903.8939307, max_length=100),
        ),
    ]
