# Generated by Django 3.2 on 2024-07-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_review_last_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='last_sms',
            field=models.CharField(default=1721663515.085749, max_length=100),
        ),
    ]
