# Generated by Django 3.2 on 2024-08-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_alter_review_last_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='last_sms',
            field=models.CharField(default=1723401027.2913861, max_length=100),
        ),
    ]
