# Generated by Django 3.2 on 2024-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subGroup',
            field=models.ManyToManyField(null=True, to='base.Subgroup'),
        ),
    ]
